language: node_js
node_js:
- '5'
env:
  matrix:
  - CXX=g++-4.8
  global:
    secure: ZGOWWxRhCMvamHldkcdGFDAa0hwrur63mqL4E3XWYoi3AXn2ctptA9JQOKgYOQoMCX8QKc2C9zvMRo/RqQb9pjuDS93Q2FgGG8SE2YWIutYtpNsj7zMmbAeyyx8vA2dt/zGNH9FEHW3zVaX93jI6KSP9JJFKQCztCFiOl1FNtCECbCr0wBMK5cEeEyKD7WiwS1ZP7pxQ2wEitbJkuZbKqYTCuWMimmNEZ0gIk4U/6IXB1XB2Gdc9CcLZ+xH9iQdmErBhEhoaZ1qZF83+/hcFeLQ5ALJyjHzqBq87qFI4c3IUPPoBW0NvO4rrMQNoDd2z/l/4SQFuzW4zJ7I/HPnAvTwQnri2379UIvzmh4Vb9XuLw5BdRFbDst0gje2LGZlo8KXQUIXLGDvk/g/HhqFSaSvhjat9slyuWc38vS2pgQX5fxIqTU0/f7XfjO6ceU7HuaRKDmRJOVm/L3B9GKf0lco+5u5vEKd/TXwS/sD0HWgse20TaH+3WTB9AWoqcj4qeDC3pKk6F4ZR95/Vm2zQh3xI8Azs8BXCyU6WTySAJQbwIffYX0HaWiNjuCVd9uy2ZAhUVZmWJxIG5SvjbZrRjrov2Y70ZcalINWT4MvddOJbb2i9zkDymTZvX1Td9esax/hgekIF8whh0aY9hcmaiqD+x5ArwuWUIUaQ7jTHPyM=
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
before_install:
- npm config set python python2.7
