sudo: false

language: node_js

notifications:
  email: false

node_js: '9'

env:
  global:
    - CC_TEST_REPORTER_ID=9bdb3725e114168adb4377551910c6c01e8e77d04b63c8b1fa5d2f75e1f461e1
  matrix:
    - CXX=g++-4.8

services:
  - docker
  - mongodb

before_install:
  - npm config set python python2.7

before_script:
  - sleep 15
  - mongo dash_test --eval 'db.createUser({user:"dashbot",pwd:"dash",roles:["readWrite","dbAdmin"]});'
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

after_script:
  - mongo --version
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - mongodb-upstart
      - mongodb-3.2-precise
    packages:
      - g++-4.8
      - mongodb-org-server
      - mongodb-org-shell
