language: node_js
node_js:
- '5'
env:
  matrix:
  - CXX=g++-4.8
  global:
    secure: u1LAiUJDpRO22kF6PXKMKdHouMZo+7/wLkkfm3eSCIyeITpvUGSFTikmi/gS0xI+ffJWVcSwmhmcA5IQQ0XDd+J8zK78Ae0InxzVsggRpreBZpEe0ZQUic4adsGqZEsYukAZQAcW02ofmMQlFRqUiFe5VskW+VMd/zg7PM7CDmmmuVKKGRIKWBoh7Jxo4nax4R46b3yRPWYG9yxwPRCWIVfft4K+RXUmLp8pFsdxWh5bQofo6SyWYLoubyMhaWVDABfWHO0NwwOlQrZpafi1j2q5FSzis76zdaZmIrEbm6n+tm5IAxFl2BpUHPFKIBzyZaI73OgSxJKmP3qQp4lft1bTSYBXr63KN+EnlPCysdRodERmqsrV0F1kom1dlmRXkxT6FjIEakdRKjTWQf95em90j+XzPh+fK83WYIlS0Z0C5TTTiyHmoqMwAsKu3SfoWgjQ+/zoXGzyrKz1oC3qDULTaZWJUAKacvPdrT7jRn0zTJsq7w/TDR8c7bHHbKBP9bYUdnagUUzNaWuqcUb+5Ng4+St3CoFYT9ue7h654Vvc3Mhk495QLga+YnGdf/17NMByR4cFgz0eZEoySaczhHxcBFpkhUG8FHg2dnrp5nc6HnWrz1CyjirQRBIdgI5VMCAPjsgg7Vc7XwhnngJrF/viToHBPqs9ymVCj/fkxp0=
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
before_install:
- npm config set python python2.7
