language: node_js
node_js:
- '5'
env:
  matrix:
  - CXX=g++-4.8
  global:
    secure: mhJ624/qx40KTGafI+JK34q3igXZAUF3dTPZ0J5gpDTCUJt4Q1S/THds8XzMGe9CCP31dVDKT0wBUUfLywDDFgaHqTCg+lA4L5GGBuIXvvcNtwQm/GXf5ZXqZ8EKkNPWay75KiP1JkfmBmv4RzLD24rVWZkdFi3qOe0l8tgYltAkMA6HK9z406OyXsd7Ab71GUjxE+CnzKu828wCvMlKYWPV9CTm55cjHWmlfTpZCndORRZXhBIzyPbsn+xQjZ2Kgw0sIFY8FX61YWsn558euDSiyk9ew9CeOMG67bWfLclBoyB3vfgOjRBOoOiNo22lgj38kg+7rnkV62WX7IpvuVIW6+KWCx1ZXCBbXuul40fxoHn25KEwimc9YgPbjg4BpXH7lW1Br8MYUW69aEgv0aLuYxq5dvA5LGlx/ShSvep9YN2i4V7nI1lj3BRJRy4AV3KVkOXZVntdWvJLk/P67rFlelTSi1Qb8hceNQo4riqRJGoP5jBFuCjxF3s+Pb5R+x+DC1c21nyel6G9zaMVqLMKxsvz3fNwSt0F8auoTc1bVYed7WTibpG1LM3pFX8qWdHPanuQRvXDw2e4oXWuyra4w+z8oLhf4PPbNKZHY3euiqRu+AooxkxgwXGWFrs8icrTmr/igYmSAegH8GC7IczrG8UkIbzyWF5oYhd2nJE=
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
before_install:
- npm config set python python2.7
