sudo: false
language: node_js
notifications:
  email: false
node_js: '6'
env:
  - CXX=g++-4.8
services:
  - docker
  - mongodb
before_install:
  - npm config set python python2.7
before_script:
  - sleep 15
after_success:
  - codeclimate-test-reporter < coverage/lcov.info
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - mongodb-upstart
      - mongodb-3.2-precise
    packages:
      - g++-4.8
      - mongodb-org-server
      - mongodb-org-shell
  code_climate:
    repo_token: 9bdb3725e114168adb4377551910c6c01e8e77d04b63c8b1fa5d2f75e1f461e1