language: node_js
node_js:
- '5'
env:
  matrix:
  - CXX=g++-4.8
  global:
    secure: Aw8Uwcki4hnxzr3PQUgo3BmSPV9M7P9QDIxnjIM+gCUAS+t3A4Wvy1QtO2/uSdhhDmSorcCXkdbIIjE7BPHVU0P5jd/N1X8w6hdSG5+ev90B8ol+Rn0xKJwkmK/omg6fjSiTmBrImXaQfWnwVISrdBC12MO2G5YhKnuY6pkfNDKtXGgAcjQ1Ypum7QqIHfowXYeEV8Bca/HXQXSWqrQ8Bp0YmC/XRYG9Gza24XGcD8jQGc/SgrXiUVLZundWTlnIOfx1g+05jESe8PI2OYDnoNgKt4a5IPONzUnera4YSJnRSbK0xcMMoyXmn3gMGc/X1+rtChvYc1k7DWv7FPBBNSwhRVoxCm4aoKsnRojuqnfECI5Vu+GYd/DdDhENC4gP0HTSPTqPihU7s6MXWW/qnmJFkoMJ0me8Ac0Q3RHMjvk+D9BRFPyGg/c5i/LZFbIT89PD5DyuD3/yEIu6zuW9SmwZJwMUo2EY40RBqkfZ2XjOVSp/Vt5UrH4DnkRReipEby7KH6RGoC1lf7jfjIWZB3/uD21YGfWBP7u9uaWzyvyvgaw/ZTMYxnBovIWeS9FfZ8dLRvaZlgMFL9MwvzYzSG3WVclqCpEwZNarEsbEO9Mj+p6pSEM9LubaZSyyNDMu0Q7fAykF9EBgevlGs48d58rEKy1xRzORAXMH+QREPjo=
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
before_install:
- npm config set python python2.7
